# Generated by Django 4.0.3 on 2022-04-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahajan',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
